name: "bert-binary-classifier-sweep"
program: "bert-binary-classifier.py"
method: bayes
metric: 
  goal: "maximize"
  name: "test.f1"
parameters: 
  learning_rate: 
    min: 0.01
    max: 0.1
  batch_size: 
    values: [16, 32, 64]
  dropout_rate: 
    min: 0.1
    max: 0.5
  weight_decay: 
    min: 0.001
    max: 0.01
  optimizer: 
    values: ['AdamW', 'RMSprop', 'SGD']
command:
  - ${env}
  - "/Users/henrywilliams/Documents/uni/anle/assessment/.venv/bin/python"
  - ${program}
  - ${args}
